import math
x = math.floor(89)
print(x)
print(int(True))
print(int(False))   # bool to int conversion #
z = math.factorial(8)
print(z)
u=(34,55,67,43,224,577,32)
print(math.sqrt(81))
print(math.trunc(90))
print(math.floor(46))
print(math.trunc(90))
print(math.fabs(4))
print(math.exp(4))
print(math.ceil(29))
print(math.log10(39))
print(math.log(9))
print(math.degrees(2*(math.pi)))
print(math.modf(67))
print(divmod(9,4))
print(max(u))
print(min(u))
print(bin(89))
print(oct(56))
print(hex(43))
